name: hev_rl
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pytorch::pytorch
  - pytorch::cudatoolkit  # 如果有GPU，可以改为 cudatoolkit
  - numpy>=1.24.0,<2.0.0
  - pandas>=2.0.0
  - scipy>=1.10.0
  - matplotlib>=3.7.0
  - pip:
    - gymnasium==0.29.1
    - stable-baselines3==2.3.2
    - shimmy>=1.3.0
    - tensorboard>=2.15.0
